[package]
name = "odin-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = ["macros", "rt", "rt-multi-thread"] }
odin-networking = { path = "./odin-networking" }
futures = "0.3.29"
message-io = { version = "0.18.0", default-features = false, features = ["tcp", "udp"]  }
log = "0.4.20"
clap = { version = "4.4.8", features = ["derive"] }
thiserror = "1.0.50"

[workspace]
members = [
    "odin-networking",
    "odin-loginserver",
]
