[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.0", features = ["macros"] }
uuid = { version = "1.11.0", features = ["v4"] }
odin-models = { path = "../../odin-models" }