use thiserror::Error;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Effect {
    Level = 1,
    Damage = 2,
    Defense = 3,
    Hp = 4,
    Mp = 5,
    Exp = 6,
    Str = 7,
    Int = 8,
    Dex = 9,
    Con = 10,
    Special1 = 11,
    Special2 = 12,
    Special3 = 13,
    Special4 = 14,
    Score14 = 15,
    Score15 = 16,
    Pos = 17,
    Class = 18,
    Req1Sidc = 19,
    Req2Sidc = 20,
    WeaponType = 21,
    ReqStr = 22,
    ReqInt = 23,
    ReqDex = 24,
    ReqCon = 25,
    AttackSpeed = 26,
    Range = 27,
    Citizen = 28,
    RunSpeed = 29,
    Spell = 30,
    Duration = 31,
    Param2 = 32,
    Grid = 33,
    Ground = 34,
    Clan = 35,
    HighWordCoin = 36,
    LowWordCoin = 37,
    Volatile = 38,
    KeyId = 39,
    Parry = 40,
    HitRate = 41,
    Critical = 42,
    Sanc = 43,
    SaveMana = 44,
    HpAdd = 45,
    MpAdd = 46,
    RegenHp = 47,
    RegenMp = 48,
    Resist1 = 49,
    Resist2 = 50,
    Resist3 = 51,
    Resist4 = 52,
    DefenseAdd = 53,
    ResistAll = 54,
    Bonus = 55,
    AttackPvp = 56,
    DefensePvp = 57,
    Quest = 58,
    Unique = 59,
    Magic = 60,
    Amount = 61,
    HighWordIndex = 62,
    LowWordIndex = 63,
    Init1 = 64,
    Init2 = 65,
    Init3 = 66,
    DamageAdd = 67,
    MagicAdd = 68,
    HpAdd2 = 69,
    MpAdd2 = 70,
    Critical2 = 71,
    DefenseAdd2 = 72,
    Damage2 = 73,
    SpecialAll = 74,
    CurKill = 75,
    LowTotKill = 76,
    HighTotKill = 77,
    Incubate = 78,
    MountLife = 79,
    MountHp = 80,
    MountSanc = 81,
    MountFeed = 82,
    MountKill = 83,
    IncubateDelay = 84,
    SubGuild = 85,
    PrevBonus = 86,
    RefLevel = 87,
    GameRoom = 88,
    AbsDamage = 89,
    AbsDefense = 90,
    Grade0 = 100,
    Grade1 = 101,
    Grade2 = 102,
    Grade3 = 103,
    Grade4 = 104,
    Grade5 = 105,
    Date = 106,
    Hour = 107,
    Min = 108,
    Year = 109,
    Month = 110,
    Transform = 112,
    Fame = 113,
    StartCol = 115,
    Color0 = 116,
    Color1 = 117,
    Color2 = 118,
    Color3 = 119,
    Color4 = 120,
    Color5 = 121,
    Color6 = 122,
    Color7 = 123,
    Color8 = 124,
    Color9 = 125,
    MaxCol = 126,
    NoSanc = 130,
    LifeSteal = 150,
    BonusExp = 151,
    PotionHeal = 152,
    BonusExpInd = 153,
    Vampirism = 154,
    IgnoreResistance = 155,
    Slow = 156,
    Resistance = 157,
    Absorption = 158,
    BonusDrop = 159,
    NoTrade = 200,
    GiftId = 201,
    DropRateBonus = 202,
    HeatIndex = 203,
}

impl From<Effect> for u8 {
    fn from(value: Effect) -> Self {
        value as u8
    }
}

impl TryFrom<u8> for Effect {
    type Error = InvalidEffect;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(match value {
            1 => Effect::Level,
            2 => Effect::Damage,
            3 => Effect::Defense,
            4 => Effect::Hp,
            5 => Effect::Mp,
            6 => Effect::Exp,
            7 => Effect::Str,
            8 => Effect::Int,
            9 => Effect::Dex,
            10 => Effect::Con,
            11 => Effect::Special1,
            12 => Effect::Special2,
            13 => Effect::Special3,
            14 => Effect::Special4,
            15 => Effect::Score14,
            16 => Effect::Score15,
            17 => Effect::Pos,
            18 => Effect::Class,
            19 => Effect::Req1Sidc,
            20 => Effect::Req2Sidc,
            21 => Effect::WeaponType,
            22 => Effect::ReqStr,
            23 => Effect::ReqInt,
            24 => Effect::ReqDex,
            25 => Effect::ReqCon,
            26 => Effect::AttackSpeed,
            27 => Effect::Range,
            28 => Effect::Citizen,
            29 => Effect::RunSpeed,
            30 => Effect::Spell,
            31 => Effect::Duration,
            32 => Effect::Param2,
            33 => Effect::Grid,
            34 => Effect::Ground,
            35 => Effect::Clan,
            36 => Effect::HighWordCoin,
            37 => Effect::LowWordCoin,
            38 => Effect::Volatile,
            39 => Effect::KeyId,
            40 => Effect::Parry,
            41 => Effect::HitRate,
            42 => Effect::Critical,
            43 => Effect::Sanc,
            44 => Effect::SaveMana,
            45 => Effect::HpAdd,
            46 => Effect::MpAdd,
            47 => Effect::RegenHp,
            48 => Effect::RegenMp,
            49 => Effect::Resist1,
            50 => Effect::Resist2,
            51 => Effect::Resist3,
            52 => Effect::Resist4,
            53 => Effect::DefenseAdd,
            54 => Effect::ResistAll,
            55 => Effect::Bonus,
            56 => Effect::AttackPvp,
            57 => Effect::DefensePvp,
            58 => Effect::Quest,
            59 => Effect::Unique,
            60 => Effect::Magic,
            61 => Effect::Amount,
            62 => Effect::HighWordIndex,
            63 => Effect::LowWordIndex,
            64 => Effect::Init1,
            65 => Effect::Init2,
            66 => Effect::Init3,
            67 => Effect::DamageAdd,
            68 => Effect::MagicAdd,
            69 => Effect::HpAdd2,
            70 => Effect::MpAdd2,
            71 => Effect::Critical2,
            72 => Effect::DefenseAdd2,
            73 => Effect::Damage2,
            74 => Effect::SpecialAll,
            75 => Effect::CurKill,
            76 => Effect::LowTotKill,
            77 => Effect::HighTotKill,
            78 => Effect::Incubate,
            79 => Effect::MountLife,
            80 => Effect::MountHp,
            81 => Effect::MountSanc,
            82 => Effect::MountFeed,
            83 => Effect::MountKill,
            84 => Effect::IncubateDelay,
            85 => Effect::SubGuild,
            86 => Effect::PrevBonus,
            87 => Effect::RefLevel,
            88 => Effect::GameRoom,
            89 => Effect::AbsDamage,
            90 => Effect::AbsDefense,
            100 => Effect::Grade0,
            101 => Effect::Grade1,
            102 => Effect::Grade2,
            103 => Effect::Grade3,
            104 => Effect::Grade4,
            105 => Effect::Grade5,
            106 => Effect::Date,
            107 => Effect::Hour,
            108 => Effect::Min,
            109 => Effect::Year,
            110 => Effect::Month,
            112 => Effect::Transform,
            113 => Effect::Fame,
            115 => Effect::StartCol,
            116 => Effect::Color0,
            117 => Effect::Color1,
            118 => Effect::Color2,
            119 => Effect::Color3,
            120 => Effect::Color4,
            121 => Effect::Color5,
            122 => Effect::Color6,
            123 => Effect::Color7,
            124 => Effect::Color8,
            125 => Effect::Color9,
            126 => Effect::MaxCol,
            130 => Effect::NoSanc,
            150 => Effect::LifeSteal,
            151 => Effect::BonusExp,
            152 => Effect::PotionHeal,
            153 => Effect::BonusExpInd,
            154 => Effect::Vampirism,
            155 => Effect::IgnoreResistance,
            156 => Effect::Slow,
            157 => Effect::Resistance,
            158 => Effect::Absorption,
            159 => Effect::BonusDrop,
            200 => Effect::NoTrade,
            201 => Effect::GiftId,
            202 => Effect::DropRateBonus,
            203 => Effect::HeatIndex,
            _ => return Err(InvalidEffect(value)),
        })
    }
}

impl Effect {
    pub fn from_name(name: &str) -> Option<Self> {
        Some(match name {
            "EF_LEVEL" => Effect::Level,
            "EF_DAMAGE" => Effect::Damage,
            "EF_AC" => Effect::Defense,
            "EF_HP" => Effect::Hp,
            "EF_MP" => Effect::Mp,
            "EF_EXP" => Effect::Exp,
            "EF_STR" => Effect::Str,
            "EF_INT" => Effect::Int,
            "EF_DEX" => Effect::Dex,
            "EF_CON" => Effect::Con,
            "EF_SPECIAL1" => Effect::Special1,
            "EF_SPECIAL2" => Effect::Special2,
            "EF_SPECIAL3" => Effect::Special3,
            "EF_SPECIAL4" => Effect::Special4,
            "EF_SCORE14" => Effect::Score14,
            "EF_SCORE15" => Effect::Score15,
            "EF_POS" => Effect::Pos,
            "EF_CLASS" => Effect::Class,
            "EF_R1SIDC" => Effect::Req1Sidc,
            "EF_R2SIDC" => Effect::Req2Sidc,
            "EF_WTYPE" => Effect::WeaponType,
            "EF_REQ_STR" => Effect::ReqStr,
            "EF_REQ_INT" => Effect::ReqInt,
            "EF_REQ_DEX" => Effect::ReqDex,
            "EF_REQ_CON" => Effect::ReqCon,
            "EF_ATTSPEED" => Effect::AttackSpeed,
            "EF_RANGE" => Effect::Range,
            "EF_CITIZEN" => Effect::Citizen,
            "EF_RUNSPEED" => Effect::RunSpeed,
            "EF_SPELL" => Effect::Spell,
            "EF_DURATION" => Effect::Duration,
            "EF_PARM2" => Effect::Param2,
            "EF_GRID" => Effect::Grid,
            "EF_GROUND" => Effect::Ground,
            "EF_CLAN" => Effect::Clan,
            "EF_HWORDCOIN" => Effect::HighWordCoin,
            "EF_LWORDCOIN" => Effect::LowWordCoin,
            "EF_VOLATILE" => Effect::Volatile,
            "EF_KEYID" => Effect::KeyId,
            "EF_PARRY" => Effect::Parry,
            "EF_HITRATE" => Effect::HitRate,
            "EF_CRITICAL" => Effect::Critical,
            "EF_SANC" => Effect::Sanc,
            "EF_SAVEMANA" => Effect::SaveMana,
            "EF_HPADD" => Effect::HpAdd,
            "EF_MPADD" => Effect::MpAdd,
            "EF_REGENHP" => Effect::RegenHp,
            "EF_REGENMP" => Effect::RegenMp,
            "EF_RESIST1" => Effect::Resist1,
            "EF_RESIST2" => Effect::Resist2,
            "EF_RESIST3" => Effect::Resist3,
            "EF_RESIST4" => Effect::Resist4,
            "EF_ACADD" => Effect::DefenseAdd,
            "EF_RESISTALL" => Effect::ResistAll,
            "EF_BONUS" => Effect::Bonus,
            "EF_ATTACKPVP" => Effect::AttackPvp,
            "EF_DEFENSEPVP" => Effect::DefensePvp,
            "EF_QUEST" => Effect::Quest,
            "EF_UNIQUE" => Effect::Unique,
            "EF_MAGIC" => Effect::Magic,
            "EF_AMOUNT" => Effect::Amount,
            "EF_HWORDINDEX" => Effect::HighWordIndex,
            "EF_LWORDINDEX" => Effect::LowWordIndex,
            "EF_INIT1" => Effect::Init1,
            "EF_INIT2" => Effect::Init2,
            "EF_INIT3" => Effect::Init3,
            "EF_DAMAGEADD" => Effect::DamageAdd,
            "EF_MAGICADD" => Effect::MagicAdd,
            "EF_HPADD2" => Effect::HpAdd2,
            "EF_MPADD2" => Effect::MpAdd2,
            "EF_CRITICAL2" => Effect::Critical2,
            "EF_ACADD2" => Effect::DefenseAdd2,
            "EF_DAMAGE2" => Effect::Damage2,
            "EF_SPECIALALL" => Effect::SpecialAll,
            "EF_CURKILL" => Effect::CurKill,
            "EF_LTOTKILL" => Effect::LowTotKill,
            "EF_HTOTKILL" => Effect::HighTotKill,
            "EF_INCUBATE" => Effect::Incubate,
            "EF_MOUNTLIFE" => Effect::MountLife,
            "EF_MOUNTHP" => Effect::MountHp,
            "EF_MOUNTSANC" => Effect::MountSanc,
            "EF_MOUNTFEED" => Effect::MountFeed,
            "EF_MOUNTKILL" => Effect::MountKill,
            "EF_INCUDELAY" => Effect::IncubateDelay,
            "EF_SUBGUILD" => Effect::SubGuild,
            "EF_PREVBONUS" => Effect::PrevBonus,
            "EF_REFLEVEL" => Effect::RefLevel,
            "EF_GAMEROOM" => Effect::GameRoom,
            "EF_ABSDAM" => Effect::AbsDamage,
            "EF_ABSAC" => Effect::AbsDefense,
            "EF_GRADE0" => Effect::Grade0,
            "EF_GRADE1" => Effect::Grade1,
            "EF_GRADE2" => Effect::Grade2,
            "EF_GRADE3" => Effect::Grade3,
            "EF_GRADE4" => Effect::Grade4,
            "EF_GRADE5" => Effect::Grade5,
            "EF_DATE" => Effect::Date,
            "EF_HOUR" => Effect::Hour,
            "EF_MIN" => Effect::Min,
            "EF_YEAR" => Effect::Year,
            "EF_MONTH" => Effect::Month,
            "EF_TRANS" => Effect::Transform,
            "EF_FAME" => Effect::Fame,
            "EF_STARTCOL" => Effect::StartCol,
            "EF_COLOR0" => Effect::Color0,
            "EF_COLOR1" => Effect::Color1,
            "EF_COLOR2" => Effect::Color2,
            "EF_COLOR3" => Effect::Color3,
            "EF_COLOR4" => Effect::Color4,
            "EF_COLOR5" => Effect::Color5,
            "EF_COLOR6" => Effect::Color6,
            "EF_COLOR7" => Effect::Color7,
            "EF_COLOR8" => Effect::Color8,
            "EF_COLOR9" => Effect::Color9,
            "EF_MAXCOL" => Effect::MaxCol,
            "EF_NOSANC" => Effect::NoSanc,
            "EF_LIFESTEAL" => Effect::LifeSteal,
            "EF_BONUSEXP" => Effect::BonusExp,
            "EF_POTIONHEAL" => Effect::PotionHeal,
            "EF_BONUSEXPIND" => Effect::BonusExpInd,
            "EF_VAMPIRISM" => Effect::Vampirism,
            "EF_IGNORERESISTANCE" => Effect::IgnoreResistance,
            "EF_SLOW" => Effect::Slow,
            "EF_RESISTANCE" => Effect::Resistance,
            "EF_ABSORPTION" => Effect::Absorption,
            "EF_BONUSDROP" => Effect::BonusDrop,
            "EF_NOTRADE" => Effect::NoTrade,
            "EF_GIFTID" => Effect::GiftId,
            "EF_DROPRATEBONUS" => Effect::DropRateBonus,
            "EF_HEATINDEX" => Effect::HeatIndex,
            _ => return None,
        })
    }
}

#[derive(Debug, Error)]
#[error("Invalid effect: {0}")]
pub struct InvalidEffect(u8);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn try_from_roundtrips() {
        let effects = [
            Effect::Level,
            Effect::Damage,
            Effect::Defense,
            Effect::Hp,
            Effect::Str,
            Effect::Special1,
            Effect::Sanc,
            Effect::LifeSteal,
            Effect::NoTrade,
            Effect::Color0,
        ];

        for effect in effects {
            let value: u8 = effect.into();
            let back = Effect::try_from(value).unwrap();
            assert_eq!(effect, back);
        }
    }

    #[test]
    fn try_from_invalid_returns_error() {
        assert!(Effect::try_from(0).is_err());
        assert!(Effect::try_from(111).is_err());
        assert!(Effect::try_from(255).is_err());
    }

    #[test]
    fn from_name_parses_known_effects() {
        assert_eq!(Effect::from_name("EF_DAMAGE"), Some(Effect::Damage));
        assert_eq!(Effect::from_name("EF_AC"), Some(Effect::Defense));
        assert_eq!(Effect::from_name("EF_STR"), Some(Effect::Str));
        assert_eq!(Effect::from_name("EF_SANC"), Some(Effect::Sanc));
        assert_eq!(Effect::from_name("EF_NOTRADE"), Some(Effect::NoTrade));
        assert_eq!(Effect::from_name("EF_NOSANC"), Some(Effect::NoSanc));
        assert_eq!(Effect::from_name("EF_BONUS"), Some(Effect::Bonus));
        assert_eq!(Effect::from_name("EF_ABSORPTION"), Some(Effect::Absorption));
    }

    #[test]
    fn from_name_returns_none_for_unknown() {
        assert_eq!(Effect::from_name("EF_UNKNOWN"), None);
        assert_eq!(Effect::from_name(""), None);
    }

    #[test]
    fn values_match_cpp_header() {
        assert_eq!(Effect::Level as u8, 1);
        assert_eq!(Effect::Damage as u8, 2);
        assert_eq!(Effect::Defense as u8, 3);
        assert_eq!(Effect::Pos as u8, 17);
        assert_eq!(Effect::Critical as u8, 42);
        assert_eq!(Effect::Sanc as u8, 43);
        assert_eq!(Effect::DefenseAdd as u8, 53);
        assert_eq!(Effect::SpecialAll as u8, 74);
        assert_eq!(Effect::Transform as u8, 112);
        assert_eq!(Effect::NoSanc as u8, 130);
        assert_eq!(Effect::LifeSteal as u8, 150);
        assert_eq!(Effect::NoTrade as u8, 200);
    }
}
